apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis            # I Pod gestiti hanno label app=redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379  # Espone Redis nel Pod (usato dal Service)
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alert-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alert-manager
  template:
    metadata:
      labels:
        app: alert-manager
    spec:
      containers:
        - name: alert-manager
          image: alert-manager:latest   # Immagine locale (caricata in Minikube)
          imagePullPolicy: Never        # Non pullare dal registry (usa l'immagine locale)
          ports:
            - containerPort: 5001       # Porta HTTP dell'API
          env:
            - name: REDIS_HOST
              value: "redis"            # Nome del Service Redis (DNS interno)
            - name: REDIS_PORT
              value: "6379"             # Porta del Service Redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-fetcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-fetcher
  template:
    metadata:
      labels:
        app: weather-fetcher
    spec:
      containers:
        - name: weather-fetcher
          image: weather-fetcher:latest
          imagePullPolicy: Never        # Usa immagine locale
          ports:
            - containerPort: 5500       # Porta Flask
          env:
            - name: ALERT_MANAGER_URL
              value: "http://alert-manager:5001/receive-alerts"  # URL interno verso alert-manager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dashboard
  template:
    metadata:
      labels:
        app: dashboard
    spec:
      containers:
        - name: dashboard
          image: dashboard:latest
          imagePullPolicy: Never        # Usa immagine locale
          ports:
            - containerPort: 3000       # Porta Express
