apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alert-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alert-manager
  template:
    metadata:
      labels:
        app: alert-manager
    spec:
      containers:
        - name: alert-manager
          image: alert-manager:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5001
          env:
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-fetcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-fetcher
  template:
    metadata:
      labels:
        app: weather-fetcher
    spec:
      containers:
        - name: weather-fetcher
          image: weather-fetcher:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5500
          env:
            - name: ALERT_MANAGER_URL
              value: "http://alert-manager:5001/receive-alerts"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dashboard
  template:
    metadata:
      labels:
        app: dashboard
    spec:
      containers:
        - name: dashboard
          image: dashboard:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
