apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: redis            # Seleziona i Pod con label app=redis
  ports:
    - port: 6379          # Porta esposta nel cluster
      targetPort: 6379    # Porta del container
  type: ClusterIP         # Solo accesso interno al cluster (nessuna esposizione esterna)
---
apiVersion: v1
kind: Service
metadata:
  name: alert-manager
spec:
  selector:
    app: alert-manager    # Seleziona i Pod con label app=alert-manager
  ports:
    - port: 5001          # Porta esposta nel cluster
      targetPort: 5001    # Porta del container (API alert-manager)
  type: ClusterIP         # Accesso interno (usato da dashboard e weather-fetcher)
---
apiVersion: v1
kind: Service
metadata:
  name: weather-fetcher
spec:
  selector:
    app: weather-fetcher  # Seleziona i Pod con label app=weather-fetcher
  ports:
    - port: 5500          # Porta esposta nel cluster
      targetPort: 5500    # Porta del container (endpoint /weather-alert)
  type: ClusterIP         # Accesso interno (usato dalla dashboard)
---
apiVersion: v1
kind: Service
metadata:
  name: dashboard
spec:
  selector:
    app: dashboard        # Seleziona i Pod con label app=dashboard
  ports:
    - port: 3000          # Porta del Service
      targetPort: 3000    # Porta del container (Express)
      nodePort: 30000     # Porta del nodo (accessibile da fuori cluster)
  type: NodePort          # Espone la dashboard all'esterno del cluster (minikube service/tunnel)
