apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: alert-manager
spec:
  selector:
    app: alert-manager
  ports:
    - port: 5001
      targetPort: 5001
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: weather-fetcher
spec:
  selector:
    app: weather-fetcher
  ports:
    - port: 5500
      targetPort: 5500
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: dashboard
spec:
  selector:
    app: dashboard
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30000
  type: NodePort
