# Base image Node.js
FROM node:20-alpine

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy app files
COPY src/alert-manager.js ./

# Expose port
EXPOSE 5001

# Start service
CMD ["npm", "start"]
